apiVersion: v1
kind: Namespace
metadata:
   name: dartgame
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dartgame-deployment
  namespace: dartgame
  labels:
    app: dartgame
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: dartgame
  template:
    metadata:
      labels:
        app: dartgame
    spec:
      containers:
      - name: dartgame
        image: haingue/dartgame:arm64
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dartgame-scale
  namespace: dartgame
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dartgame-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1beta1
        kind: Ingress
        name: dartgame-ingress
      target:
        type: Value
        value: 1k
---
apiVersion: v1
kind: Service
metadata:
  name: dartgame-service
  namespace: dartgame
  labels:
    app: dartgame
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: dartgame
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dartgame-ingress
  namespace: dartgame
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dartgame.haingue.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dartgame-service
            port:
              number: 80
